accounts/urls.py
from .views import login_view, logout_view, signup_view
from django.urls import path

urlpatterns = [
    path('login', login_view, name='login'),
    path('logout', logout_view, name='logout'),
    path('signup', signup_view, name='signup'),
]

my_store/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('products.urls')),
    path('accounts/', include('accounts.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.contrib import admin
from django.urls import path

from .views import index, get_product, add_new_comment

urlpatterns = [
    path('', index, name='index'),
    path('product/<int:id>', get_product, name='get_product'),
    path('product/<int:id>/add_new_comment', add_new_comment, name='add_new_comment'),
]

accounts/models.py
from django.db import models

# Create your models here.

products/models.py
from django.db import models
from django.utils import timezone

class Product(models.Model):
    name = models.CharField(max_length=100)
    price = models.DecimalField(decimal_places=2, max_digits=10)
    sku = models.CharField(max_length=10)
    category = models.CharField(max_length=50)
    brand = models.ForeignKey(
        'products.Brand',
        on_delete=models.CASCADE,  # If the referenced object is deleted,
        related_name='products'
    )
    image = models.ImageField(
        blank=True,
        upload_to='media/products',
        null=True
        )
    discount = models.IntegerField()
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)

    def __str__(self):
        return f'{self.name} | {self.brand}'

class Brand(models.Model):
    name = models.CharField(max_length=30)
    description = models.TextField(null=True, blank=True)
    logo = models.ImageField(
        blank=True,
        upload_to='media/logo/products',
        null=True
        )
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)

    def __str__(self):
        return self.name
    

class Comment(models.Model):
    product = models.ForeignKey(
        'products.Product',
        on_delete=models.CASCADE,
        related_name= 'comments'
    )
    author = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    approved_comment = models.BooleanField(default=False)

    def approve(self):
        self.approved_comment = True
        self.save()

    def __str__(self):
        return self.text

products/forms.py
from django import forms
from django.forms import ModelForm, Textarea

from .models import Comment

class CommentsForm(ModelForm):
    
    class Meta:
        model = Comment

        fields = ('text',)
        widgets = {
            'text': Textarea(attrs={
                'class': 'form-control',
                'aria-label': 'Comentarios',
                'placeholder': 'Deja un comentario',
                'id': 'formComment',
            }),
        }

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth import login, logout

def signup_view(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('index')
    
    else:
        form = UserCreationForm()
    
    return render(request, 'accounts\signup.html', {
        'form': form
        })

def login_view(request):
    
    if request.method == "POST":
        form = AuthenticationForm(data=request.POST)
        if  form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('index')

    else:
        form = AuthenticationForm()
    
    return render(request, 'accounts/login.html', {
        'form': form,
    })

def logout_view(request):
    if request.method == "POST":
        logout(request)
        return redirect('index')

products/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required, permission_required
from .models import Product, Comment
from .forms import CommentsForm

def index(request):
    products = Product.objects.all()

    return render(request, 'products/list_of_products.html', {
        'products': products,
    })

def get_product(request, id):
    product = Product.objects.get(id=id)
    comment = Comment.objects.filter(product=id)
    form = CommentsForm()

    return render(request, 'products/show_product.html', {
        'product': product,
        'comments': comment,
        'form': form,
    })

@login_required
@permission_required('products.add_comment', raise_exception=True)
def add_new_comment(request, id):
    if request.method == 'POST':
        form = CommentsForm(request.POST)
        product = Product.objects.get(id=id)
        if form.is_valid():
            user = request.user
            new_comment = form.save(commit=False)
            new_comment.author = user
            new_comment.product = product
            new_comment.save()
    return redirect('get_product', id)

templates/accounts/login.html
{% extends 'base/base.html' %}
{% block content %}
<div class="login-container container">
    <div class="card">
        <div class="card-body">
            <h1 class="text-center mb-5">
                Login
            </h1>
            <form action="{% url 'login' %}" method="post">
                {% csrf_token %}
                {{ form }}
                <input class="btn btn-tomato" type="submit" value="Ingresar" />
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/accounts/signup.html
{% extends "base/base.html" %}
{% block content %}
<div class="login-container container">
    <div class="card">
        <div class="card-body">
            <h1 class="text-center mb-5">Signup</h1>

            <form action={% url 'signup' %} method="post">
                {% csrf_token %}
                {{ form }}
                <input class="btn submit-btn btn-tomato" type="submit" value="Sigup">
            </form>

        </div>
    </div>
</div>
{% endblock content %}

templates/base/base.html
{% load static %}

<html lang="es">

<head>
    <title>Tienda del Barrio</title>
    <meta name="description" content="Mi primera tienda de barrio virtual">
    <meta name="keywords" content="ecomerce,market">
    {# Bootstrap - https://getbootstrap.com/#}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
    {# Fonts #}
    <link href="https://fonts.googleapis.com/css?family=Montserrat:wght@400;700&display=swap" rel="stylesheet">
    {# Styles #}
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>

<body>

    {% include './navigation.html' %}

    {% block content %}
    {% endblock %}

</body>

</html>

templates/base/navigation.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <a href="{% url 'index' %}" class="navbar-brand"> Tienda del Barrio</a>
    </div>
    <ul class="navbar-nav">
        {% if user.is_authenticated %}
        <li class="nav-item">
            <a href="" class="nav-link" tabindex="-1">
                {{ user.username }}
            </a>
        </li>
        <li class="nav-item">
            <form action={% url 'logout' %} method="post">
                {% csrf_token %}
                <button type="submit" class="btn btn-outline-danger me-2" tabindex="-2">Cerrar sesión</button>
            </form>
        </li>
        {% else %}
        <li class="nav-item">
            <a href="{% url 'login' %}" class="btn btn-outline-danger me-2" tabindex="-1" aria-disabled="true">
                Ingresar
            </a>
        </li>
        {% endif %}
    </ul>
</nav>

templates/products/list_of_products.html
{% extends 'base/base.html' %}

{% block content %}
<div class="container">
    <div class="row">
        {% for product in products %}
        <div class="col-3">
            <div class="card">
                <img src="{{ product.image.url }}" class="card-img-top float-start" style="height: 180; width: 180">
                <div class="card-body">
                    <h5 class="card-title">{{ product.name }}</h5>
                    <div class="price-container">
                        <p class="card-title">
                            <s>{{ product.discount }}</s>
                        </p>
                        <p class="card-title product-price">{{ product.price }}</p>
                    </div>
                    <p class="card-text">
                        {{ product.sku }}
                    </p>
                    <a class="btn btn-successful" href="{% url 'get_product' id=product.id %}"
                        style="background-color: tomato;">Leer más</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

templates/products/show_product.html
{% extends 'base/base.html' %}
{% block content %}
<div class="container">
    <div class="row product-detail-row mt-4 mb-5">
        <div class="col-5">
            <img src="{{ product.image.url }}" class="img-fluid" height="" alt="{{ product.image.alt }}">
        </div>
        <div class="col-7">
            <div class="jumbotron">
                <h1 class="display-4"> {{ product.name }} </h1>
                <div class="price-container">
                    <h5 class="card-title">{{ product.price }} USD</h5>
                </div>
                <hr class="my-4">
                <p>
                    {{ product.brand.description }}
                </p>

                <a class="btn btn-tomato" href="/">Añadir al carrito</a>
            </div>
        </div>
    </div>
    {% if perms.products.add_comment %}
    <div class="row">
        <div class="col-5 comment-column">
            <form action="{% url 'add_new_comment' id=product.id %}" method="post" class="post-form">
                {% csrf_token %}
                <div class="input-group mb-4">
                    {{ form.text }}
                </div>
                <button type="submit" class="save btn btn-dark">Comentar</button>
            </form>
        </div>
    </div>
    {% endif %}

    {% if perms.products.view_comment %}
    <div class="col-7">
        <h2 class="comment-title text-left">Comentarios</h2>
        {% for comment in comments %}
        <div class="comment">
            <div class="date">{{ comment.created_date }}</div>
            <strong>{{ comment.author }}</strong>
            <p>{{ comment.text }}</p>
        </div>
        {% endfor %}
    </div>
    {% endif %}
</div>
{% endblock %}